import { TextStyle } from "pixi.js";

export class TextStyles {
    public static readonly TITLE = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 100,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#FFD700', '#F0E68C'], 
        stroke: '#FEBE10',
        strokeThickness: 5,
        dropShadow: true,
        dropShadowBlur: 4,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 6,
        wordWrap: true,
        wordWrapWidth: 1260,
        lineJoin: 'round',
    });
    public static readonly SELECT_BET = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 28,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#ffffff', '#94bbe9'], 
        stroke: '#94bbe9',
        strokeThickness: 2,
        dropShadow: true,
        dropShadowBlur: 4,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 6,
        wordWrap: true,
        wordWrapWidth: 1000,
        lineJoin: 'round',
    });
    public static readonly CREDIT = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 40,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#FFD700', '#F0E68C'], 
        stroke: '#FEBE10',
        strokeThickness: 2,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 3,
        wordWrap: true,
        wordWrapWidth: 350,
        lineJoin: 'round',
    });
    public static readonly AMOUNT = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 40,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#E44D2E', '#C6011F'], 
        stroke: '#8B0000',
        strokeThickness: 2,
        dropShadow: true,
        dropShadowColor: '#002D62',
        dropShadowBlur: 2,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 3,
        wordWrap: true,
        wordWrapWidth: 350,
        lineJoin: 'round',
    });
    public static readonly CHIP = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 75,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#FFD700', '#F0E68C'], 
        stroke: '#4a1850',
        strokeThickness: 5,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 6,
        wordWrap: true,
        wordWrapWidth: 350,
        lineJoin: 'round',
    });
    public static readonly GAME_MSG = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 50,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#E25822', '#FF4500'], 
        stroke: '#8B0000',
        strokeThickness: 5,
        dropShadow: true,
        dropShadowColor:0xFFFFFF,
        dropShadowBlur: 10,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 6,
        wordWrap: true,
        wordWrapWidth: 1100,
        lineJoin: 'round',
        align:'center'
    });
    public static readonly RESULT = new TextStyle({
        fontFamily: 'Arial',
        fontSize: 45,
        fontStyle: 'italic',
        fontWeight: 'bold',
        fill: ['#E44D2E', '#C6011F'], 
        stroke: '#8B0000',
        strokeThickness: 2,
        dropShadow: true,
        dropShadowBlur: 2,
        dropShadowAngle: Math.PI / 6,
        dropShadowDistance: 6,
        wordWrap: true,
        wordWrapWidth: 350,
        lineJoin: 'round',
    });
}
